# Generated by Django 4.1.7 on 2023-03-08 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='complted',
            new_name='completed',
        ),
    ]
